CREATE TABLE plans (
    pid INT PRIMARY KEY AUTO_INCREMENT,
    cid INT NOT NULL,
    plan_name_system VARCHAR(100) NOT NULL,
    web_display_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (cid) REFERENCES carrier_info(cid)
);
